export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_USER = "AUTH_USER";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const CHANGE_USER = "CHANGE_USER";

export const FETCH_PIZZA_SUCCESS = "FETCH_PIZZA_SUCCESS";
export const FETCH_PIZZA = "FETCH_PIZZA";
export const FETCH_DRINKS_SUCCESS = "FETCH_DRINKS_SUCCESS";
export const FETCH_DRINKS = "FETCH_DRINKS";
export const FETCH_SIDES_SUCCESS = "FETCH_SIDES_SUCCESS";
export const FETCH_SIDES = "FETCH_SIDES";
export const FETCH_DESSERT_SUCCESS = "FETCH_DESSERT_SUCCESS";
export const FETCH_DESSERT = "FETCH_DESSERT";
export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_PRODUCT_FAILED = "FETCH_PRODUCT_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const INCREMENT_CART_ITEM_QUANTITY = "INCREMENT_CART_ITEM_QUANTITY"
export const DECREMENT_CART_ITEM_QUANTITY = "DECREMENT_CART_ITEM_QUANTITY"
export const UPDATE_AMOUNT = "UPDATE_AMOUNT";
export const COUNT_ITEM = "COUNT_ITEM";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART"

export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";

export const PURCHASE_ORDER = "PURCHASE_ORDER";
export const PURCHASE_ORDER_START = "PURCHASE_ORDER_START";
export const PURCHASE_ORDER_FAILED = "PURCHASE_ORDER_FAILED";
export const PURCHASE_ORDER_SUCCESS = "PURCHASE_ORDER_SUCCESS";