export const TPHCM = 
    [
        {
            name: 'District 1',
            address: [
                'Bmc-Vo Van Kiet-P.Cau Kho',
                'Co Bac-P.Cau Ong Lanh',
                'Co Bac-P.Co Giang',
                'Co Giang-P.Cau Ong Lanh',
                'Co Giang-P.Co Giang',
                'De Tham-P.Cau Ong Lanh',
                'De Tham-P.Co Giang',
                'Ho Hao Hon-P.Co Giang',
                'Nguyen Canh Chan-P.Cau Kho',
                'Nguyen Khac Nhu-P.Co Giang',
                'Nguyen Van Cu-P.Cau Kho',
                'Tran Dinh Xu-P.Cau Kho',
                'Tran Dinh Xu-P.Co Giang',
                'Nam Quoc Cang-P.Pham Ngu Lao',
                'Nguyen Trai-P.Nguyen Cu Trinh'
            ]
        },
        {   
            name: 'District 2',
            address: [
                'An Phu-P.An Phu',
                'Ava Residence-P.Thao Dien',
                'A-P.Binh Khanh',
                'D1-P.Binh An',
                'Greenfield Compound-P.Binh An',
                'Babylon 1 Newcity-P.Binh Khanh',
                'Babylon 2 Newcity-P.Binh Khanh',
                'Babylon 3 Newcity-P.Binh Khanh',
                'Bac Nam - KDT Thu Thiem',
                'Bali 1 Newcity- P.Binh Khanh'
            ]
        },
        {
            name: 'District 3',
            address: [
                'Le Van Sy -P.12',
                'Le Van Sy -P.13',
                'Le Van Sy -P.14',
                'Tran Quang Dieu -P.13',
                'Tran Quang Dieu -P.14',
                'Truong Sa -P.12',
                'Truong Sa -P.13',
                'Truong Sa -P.14',
                'Chau Thoi',
                'Doan Cong Buu-P.7',
                'Hoang Sa-P.11',
                'Hoang Sa-P.7',
                'Hoang Sa-P.9',
                'Ky Dong-P.9',
                'Ly Thuong Kiet',
                'Nguyen Phuc Nguyen -P.10',
                'Nguyen Phuc Nguyen - P.9'
            ],
        },
        {
            name: 'District 4',
            address: [
                'Ben Van Don-P.12',
                'Ben Van Don-P.5',
                'Ben Van Don-P.6',
                'Ben Van Don-P.9',
                'Dinh Le-P.12',
                'Doan Nhu Hai-P.12',
                'Doan Van Bo -P.10',
                'Doan Van Bo- P.14',
                'Doan Van Bo -P.16',
                'Hoang Dieu-P.12',
                'Hoang Dieu-P.13',
                'Hoang Dieu-P.6',
                'Hoang Dieu-P9',
                'Khanh Hoi-P.3',
                'Khanh Hoi-P.4',
                'Khanh Hoi-P.5',
                'Khanh Hoi-P.6',
                'Le Quoc Hung -P.12'
            ],
        },
        {
            name: 'District 5',
            address: [
                'An Binh-P.5',
                'An Binh-P.6',
                'An Binh-P.7',
                'An Diem-P.10',
                'An Duong Vuong -P.13',
                'An Duong Vuong -P.3',
                'An Duong Vuong -P.4',
                'An Duong Vuong -P.8',
                'An Duong Vuong -P.9',
                'An Duong Vuong -So Chan -P.9',
                'Bach Van -P.5',
                'Bui Huu Nghia -P.5',
                'Bui Huu Nghia -P.7',
                'Cc 43 An Binh-An Binh - P.6',
                'Cc Bien Dong -Tran Hung Dao -P.6',
                'Cc Ngo Quyen - Ngo Quyen -P.9',
                'Cc NguyenTrai- Phuoc Hung -P.8',
                'Cc Tan Da',
                'Cc Tran Hung Dao - Tran Hung Dao B-P.14',
                'Hung Vuong-P.2',
                'Hung Vuong-P.9',
                'Hung Vuong-P.3',
                'Hong Bang-P.12'
            ]
        },
        {
            name: 'District 6',
            address: [
                '3 Thang 2 -P.12',
                'Binh Tay -P.1',
                'Cong Chua Ngoc Han -P.12',
                'Go Cong -P.11',
                'Huyen Toai -P.12',
                'Kim Bien -P.1',
                'KIm Bien -P.13',
                'Le Tan Ke -P2',
                'Lo Sieu-P.12',
                'Nguyen Huu Than -P.2',
                'Nguyen Thi Nho -P.2',
                'Vo Van Kiet -P.14',
                'Vo Van Kiet -P.15',
                'An Duong Vuong -P.10',
                'An Duong Vuong -P.12',
                'Tue Tinh -P.12',
                'Binh Thoi -P.10',
                'Binh Thoi -P.9',
                'Cao Van Lau -P.1',
                'Cao Van Lau -P.2',
            ]
        },
        {   
            name: "District 7",
            address: [
                '6 My Duc',
                '71-P.Tan Quy Dong',
                'Broadway A-Nguyen Luong Bang',
                'Broadway B-Nguyen Luong Bang',
                'Broadway C-Nguyen Luong Bang',
                'Broadway D-Nguyen Luong Bang',
                'Bui Bang Doan',
                'Canh Vien 1 Block A',
                'Canh Vien 1 Block B',
                'Canh Vien 1 - Nguyen Luong Bang',
                'Canh Vien 2 Block A',
                'Canh Vien 2 Block B',
                'Canh Vien 2 - Nguyen Luong Bang',
                'Canh Vien 3 Block A',
                'Canh Vien 3 Block B',
                'Canh Vien 3 - Nguyen Luong Bang',
                'Garden Plaza 1-Block A',
                'Garden Plaza 1-Block B',
                'Garden Plaza 1-Block C',
                'Garden Plaza 1-Block D',
                'Garden Plaza 1-Ton Dat Tien',
                'Garden Plaza 2',
                'Garden Plaza 2-Ton Dat Tien',
                'Gragon Hill-Block A',
                'Gragon Hill-Block B',
                'Gragon Hill-Nguyen Huu Tho',
                'Grand View A-Block A',
                'Grand View A-Block B',
                'Grand View A-Block C',
                'Grand View A-Block D',
                'Grand View A-Nguyen Duc Canh',
                'Grand View B-Block A',
                'Grand View B-Block B',
                'Grand View B-Block C',
                'Grand View B-Block D',
                'Grand View B-Nguyen Duc Canh',
            ],
        },
        {
            name: "District 8",
            address: [
                'An Duong Vuong - P.16',
                'Cc Carina -P.16',
                'Cc My Thuan -P.16',
                'Vo Van Kiet -P.16',
                '7 Kdc Trung Son',
                'Au Duong Lan-P.2',
                'Au Duong Lan-P.3',
                'Da Nam-P.2',
                'Dang Chat-P.2',
                'Dang Chat-P.3',
                'De Tham-P.Cau Ong Lanh',
                'Duong Ba Trac-P.1',
                'Duong Ba Trac-P.2',
                'Duong Ba Trac-P.3',
                'Nguyen Lam Tower-P.3',
                'Pham The Hien-P.2',
                'Pham The Hien-P.3',
                'So 9 -P.3',
                'Ta Quang Buu -P.2',
                'Ta Quang Buu -P.3',
                'Ba Dinh-P.10',
                'Ba Dinh-P.9',
                'Ben Binh Dong -P.11',
                'Ben Binh Dong -P.13'
                
            ]
        },
        {
            name: 'District 9',
            address: [
                'Chung cu Eastern',
                'Chung cu Ehome 1 -P.Phuoc Long B',
                'Cau Xay 2-P.Tan Phu',
                'Chu Van An -P.Hiep Phu',
                'Chung cu Man Thien -C1.P.Tang Nhon Phu A',
                'Chung cu Man Thien -C2.P.Tang Nhon Phu A',
                'Chung cu Man Thien -C3.P.Tang Nhon Phu A',
                'Chung cu Man Thien -C4.P.Tang Nhon Phu A',
                'Chung cu Man Thien -C5.P.Tang Nhon Phu A',
                'Chung cu Man Thien -C6.P.Tang Nhon Phu A',
                'Chung cu Man Thien -C8.P.Tang Nhon Phu A',
                'Co Bac-P.Hiep Phu',
                'Co Giang-P.Hiep Phu',
                'Ngo Quyen -P.Hiep Phu',
                'Ham Nghi -P.Hiep Phu'
            ],
        },
        {
            name: 'District 10',
            QUAN10: [
                'Ba Hat -P.4',
                'Ba Hat -P.6',
                'Ba Hat -P.8',
                '3 Thang 2-So Chan-P.12',
                '3 Thang 2-So Le-P.12',
                'Ly Thuong Kiet -P.12',
                'Ly Thuong Kiet -P.14',
                'Ly Thuong Kiet -P.15',
                'Ly Thuong Kiet -P.7',
                'Hoa Hao',
                'Nguyen Chi Thanh -P.9',
                'Nguyen Chi Thanh -P.3',
                'Nguyen Chi Thanh -P.5',
                'Nguyen Duy Duong -P.3',
                'Nguyen Duy Duong -P.4',
                'Nguyen Kim',
                'Nguyen Kim -P.6',
                'Nguyen Kim -P.7',
                'Nguyen Thuong Hien -P.11',
                'Nguyen Tri Phuong-P.4',
                'Nguyen Tri Phuong-P.5',
                'Nguyen Tri Phuong-P.8',
                'Nguyen Tri Phuong-P.9',
            ]
        },
        {
            name: 'District TanBinh',
            address: [
                'Lac Long Quan -P13',
                'Lac Long Quan -P9',
                'Ly Thuong Kiet -P.10',
                'Ly Thuong Kiet -P.8',
                'Ap Bac -P.13',
                'A4-P.12',
                'Bau Cat',
                'Bau Cat 1-P.14',
                'Bau Cat 2-P.12',
                'Bau Cat 3-P.12',
                'Bau Cat 3-P.14',
                'Bau Cat 4-P.14',
                'Bau Cat 5-P.14',
                'Bau Cat 6-P.14',
                'Bau Cat 7-P.14',
                'Bau Cat 8-P.14',
                'Bau Cat 9-P.11',
                'Truong Chinh-So Chan-P.13',
                'Truong Son',
                'Dong Den',
                'Cong Hoa',
                'Cong Hoa -P.12',
                'Cong Hoa -P.13',
                'Cong Hoa -P.15',
                'Cong Hoa -P.4'
            ]
        }
    ]
    export const HANOI = [
        {
            name: 'District Ba Dinh',
            address:[
                'Au Co So-Chan-P.10',
                'Au Co So-Chan-P.9',
                'Bui The My',
                'Bui The My P.10',
                'Dong Ho',
                'Duy Tan P.8',
                'Lac Long Quan-P.13',
            ]
        },
        {
            name: 'District Cau Giay',
            address: [
                'AR1-P.Trung Hoa',
                'AR2-P.Trung Hoa',
                'AR5-P.Trung Hoa',
                'AR6-P.Trung Hoa',
                'AR7-P.Yen Hoa',
                'Duong Dinh Nghe -P.Yen Hoa',
                'Tran Thai Tong - P.Dich Vong Hau'
            ]
        }
    ]
      